apiVersion: v1
kind: Service
metadata:
  name: node-k8s-demo
  labels:
    app: node-k8s-demo
spec:
  type: ClusterIP
  selector:
    app: node-k8s-demo
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
